### ISSUE TITLE
[BUG] Sign up not working

### ISSUE THREAD

**Issue by viinkelvin** [ninja-stack/a-zhare#62]
## Bug Description
User can't sign up after input correct data

## How to reproduce
1. Go to /signup page
2. Input user full name correctly
3. Input gender correctly
4. Input non existing email correctly
5. Input password correctly
6. Input confirm password correctly (should be the same with password)
7. Click SIGN UP button

## Expected Behavior
Sign Up success, and it redirect to dashboard

**Comment by ZendyLim** [comment]
Done
